import 'package:safari_app/model/Trip.dart';
import 'model/Category.dart';

const Categories_data = [
  Category(
    id: 'c1',
    title: 'جبال',
    imageUrl:
        'https://images.unsplash.com/photo-1575728252059-db43d03fc2de?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NTh8fG1vdW5hdGluc3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=',
  ),

  Category(
    id: 'c2',
    title: 'بحيرات',
    imageUrl:
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c3',
    title: 'شواطىء',
    imageUrl:
        'https://images.unsplash.com/photo-1493558103817-58b2924bce98?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTAxfHxiZWFjaHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c4',
    title: 'صحارى',
    imageUrl:
        'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8ZGVzZXJ0fGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c5',
    title: 'مدن تاريخية',
    imageUrl:
        'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NjR8fHRyYXZlbHxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
  Category(
    id: 'c6',
    title: 'أخرى',
    imageUrl:
        'https://images.unsplash.com/photo-1605540436563-5bca919ae766?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8c2tpaW5nfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60',
  ),
];
const Trips_data = [
  Trip(
    id: 'm1',
    categories: ['c1'],
    title: 'جبال الألب',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1611523658822-385aa008324c?auto=format&fit=crop&w=500&q=60',
    duration: 20,
    activities: ['تسلق الجبال', 'زيارة المواقع الأثرية', 'التنزه في الثلوج'],
    program: ['يوم كامل في الجبال مع جولة مصورة.', 'غداء في مطعم جبلي.'],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm2',
    categories: ['c1'],
    title: 'جبال الجنوب',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1612456225451-bb8d10d0131d?auto=format&fit=crop&w=500&q=60',
    duration: 10,
    activities: ['تسلق', 'تخييم', 'مشاهدة الثلوج'],
    program: ['رحلة قصيرة مع مرشد.'],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm3',
    categories: ['c1'],
    title: 'جبال مرتفعة',
    tripType: TripType.Recovery,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1592221912790-2b4df8882ea9?auto=format&fit=crop&w=500&q=60',
    duration: 45,
    activities: ['مشاهدة المناظر', 'التزلج', 'التخييم'],
    program: ['يوم استرخاء في المنتجع الجبلي.'],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm4',
    categories: ['c2', 'c1'],
    title: 'البحيرة الكبرى',
    tripType: TripType.Activities,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=500&q=60',
    duration: 60,
    activities: ['السباحة', 'ركوب القارب', 'التصوير'],
    program: ['رحلة في القارب وزيارة جزيرة صغيرة.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm5',
    categories: ['c2', 'c1'],
    title: 'البحيرات الصغرى',
    tripType: TripType.Activities,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1580100586938-02822d99c4a8?auto=format&fit=crop&w=600&q=60',
    duration: 15,
    activities: ['نزهة عائلية', 'سباحة', 'تصوير الطبيعة'],
    program: ['استراحة عائلية على ضفاف البحيرة.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm6',
    categories: ['c2'],
    title: 'بحيرة الزمرد',
    tripType: TripType.Exploration,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=600&q=60',
    duration: 240,
    activities: ['رحلة قارب', 'استجمام', 'غوص'],
    program: ['جولة بحرية مع وجبة غداء.'],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm7',
    categories: ['c3'],
    title: 'شاطئ الأول',
    tripType: TripType.Exploration,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=600&q=60',
    duration: 20,
    activities: ['السباحة', 'الاستجمام على الشاطئ', 'كرة الشاطئ'],
    program: ['يوم كامل على الشاطئ.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm8',
    categories: ['c3'],
    title: 'الشاطئ الكبير',
    tripType: TripType.Recovery,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=500&q=60',
    duration: 35,
    activities: ['استرخاء', 'سباحة', 'تنس شاطئي'],
    program: ['منتجع شامل على البحر.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm9',
    categories: ['c3'],
    title: 'شاطئ الصخور',
    tripType: TripType.Exploration,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1519602035691-16ac091344ef?auto=format&fit=crop&w=600&q=60',
    duration: 45,
    activities: ['تسلق الصخور', 'سباحة', 'تصوير'],
    program: ['رحلة مغامرة على الشاطئ الصخري.'],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm10',
    categories: ['c4'],
    title: 'الصحراء الكبرى',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?auto=format&fit=crop&w=500&q=60',
    duration: 30,
    activities: ['جولة سيارات دفع رباعي', 'تصوير الغروب'],
    program: ['رحلة في الصحراء مع غروب الشمس.'],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm11',
    categories: ['c4', 'c1'],
    title: 'الصحراء الغربية',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['سفاري', 'ركوب الجمال'],
    program: ['جولة استكشافية في الصحراء الغربية.'],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm12',
    categories: ['c4'],
    title: 'الصحراء الرملية',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1452022582947-b521d8779ab6?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['ركوب الجمال', 'التصوير', 'الاستجمام في المخيم'],
    program: ['رحلة يومية في الصحراء الرملية.'],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm13',
    categories: ['c5'],
    title: 'المدينة الأولى',
    tripType: TripType.Activities,
    season: Season.Spring,
    imageUrl:
        'https://images.unsplash.com/photo-1498307833015-e7b400441eb8?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['زيارة معالم المدينة', 'التسوق', 'غداء في مطعم محلي'],
    program: ['جولة داخل المدينة مع دليل سياحي.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm14',
    categories: ['c5'],
    title: 'المدينة الثانية',
    tripType: TripType.Activities,
    season: Season.Spring,
    imageUrl:
        'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['جولة بالباص السياحي', 'زيارة الأسواق'],
    program: ['جولة مريحة ومناسبة للعائلات.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm15',
    categories: ['c5'],
    title: 'المدينة القديمة',
    tripType: TripType.Activities,
    season: Season.Spring,
    imageUrl:
        'https://images.unsplash.com/photo-1519923041107-e4dc8d9193da?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['زيارة المعالم الأثرية', 'التسوق التقليدي'],
    program: ['يوم في الأسواق التاريخية.'],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: false,
  ),
  Trip(
    id: 'm16',
    categories: ['c6'],
    title: 'رياضة التزلج',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl:
        'https://images.unsplash.com/photo-1605540436563-5bca919ae766?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['تزلج على الجليد', 'تدريب على التوازن'],
    program: ['يوم رياضي في منتجع التزلج.'],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm17',
    categories: ['c6', 'c2'],
    title: 'القفز المظلي',
    tripType: TripType.Activities,
    season: Season.Summer,
    imageUrl:
        'https://images.unsplash.com/photo-1601024445121-e5b82f020549?auto=format&fit=crop&w=600&q=60',
    duration: 30,
    activities: ['تجربة القفز بالمظلة', 'التصوير الجوي'],
    program: ['نشاط مغامرة لمحبي الإثارة.'],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
];
