name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # Cache pub packages to speed up runs (include Flutter version in the key)
      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .dart_tool
          key: ${{ runner.os }}-pub-3.19.0-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-3.19.0-

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Flutter
        run: flutter --version

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
